const TodoActionTypes = {
  FETCH_TODO_START: 'FETCH_TODO_START',
  FETCH_TODO_SUCCESS: 'FETCH_TODO_SUCCESS',
  FETCH_TODO_FAILURE: 'FETCH_TODO_FAILURE',

  ADD_TODO_START: 'ADD_TODO_START',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',

  REMOVE_TODO: 'REMOVE_TODO'
};

export default TodoActionTypes;
